name: skincraft_mvp2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fluentui_system_icons: ^1.1.248
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6
  image_picker: ^1.1.2
  modal_progress_hud_nsn: ^0.5.1
  pinput: ^5.0.0
  provider: ^6.1.2
  simple_barcode_scanner: ^0.1.1
  syncfusion_flutter_charts: ^23.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/image/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/poppins/Poppins-Regular.ttf
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
